box1:
    x: -0.45
    y: -0.03
    z: 0.015

    rx: 0
    ry: 0
    rz: 0.5
box2:
    x: -0.45
    y: 0.07
    z: 0.015

    rx: 0
    ry: 0
    rz: 0.5
box3:
    x: -0.45
    y: 0.17
    z: 0.015

    rx: 0
    ry: 0
    rz: 0.5
box4:
    x: -0.45
    y: 0.27
    z: 0.015

    rx: 0
    ry: 0
    rz: 0.5
box5:
    x: -0.13
    y: -0.03
    z: 0.015

    rx: 0
    ry: 0
    rz: -0.5
box6:
    x: -0.13
    y: 0.07
    z: 0.015

    rx: 0
    ry: 0
    rz: -0.5
box7:
    x: -0.13
    y: 0.17
    z: 0.015

    rx: 0
    ry: 0
    rz: -0.5
box8:
    x: -0.13
    y: 0.27
    z: 0.015

    rx: 0
    ry: 0
    rz: -0.5
