box1:
    x: -0.4
    y: -0.3
    z: 0.015

    rx: 0
    ry: 0
    rz: 0.5
box2:
    x: -0.4
    y: -0.15
    z: 0.015

    rx: 0
    ry: 0
    rz: 0.5
box3:
    x: -0.4
    y: 0
    z: 0.015

    rx: 0
    ry: 0
    rz: 0.5
box4:
    x: -0.4
    y: 0.15
    z: 0.015

    rx: 0
    ry: 0
    rz: 0.5

